dictionaries:
  - en
  - pt_BR

excluded_files:
  - "vendor/**/*"
  - "node_modules/**/*"
  - "*.key"
  - "*.enc"
  - "*.min.css"
  - "*.css.map"
  - "*.min.js"
  - "*.js.map"
  - "*.mk"
  - "package-lock.json"
  - "yarn.lock"
  - "Gemfile.lock"
  - ".typo-ci.yml"

excluded_words:
  - aparência
  - assédio
  - através
  - código
  - codigo-de-conduta
  - cooperação
  - crença
  - critério
  - deficiência
  - dev
  - discriminação
  - divulgação
  - espaço
  - experiência
  - física
  - gemfile
  - gênero
  - lajimmy_andrade
  - não
  - Nós
  - organização
  - orientação
  - participação
  - raça
  - são
  - será
  - testc
  - testu
  - testw
  - typoci
  - Versão
  - Você
  - voluntárias
