dictionaries:
  - en
  - pt_BR

excluded_files:
  - "vendor/**/*"
  - "node_modules/**/*"
  - "*.key"
  - "*.enc"
  - "*.min.css"
  - "*.css.map"
  - "*.min.js"
  - "*.js.map"
  - "*.mk"
  - "package-lock.json"
  - "yarn.lock"
  - "Gemfile.lock"
  - ".typo-ci.yml"

excluded_words:
  - ação
  - alguém
  - aparência
  - aprender
  - área
  - assédio
  - atenção
  - através
  - Atribuição
  - botão
  - caráter
  - codigo
  - código
  - codigo-de-conduta
  - comentários
  - concorda
  - Conduta
  - contrários
  - cooperação
  - créditos
  - crença
  - critério
  - deficiência
  - dev
  - discriminação
  - discriminatória
  - divulgação
  - duração
  - Educodar
  - espaço
  - espaços
  - está
  - experiência
  - expulsão
  - física
  - físico
  - formik
  - gemfile
  - gênero
  - iml
  - inglês
  - inscrever
  - interrupções
  - intimidação
  - íntimo
  - lajimmy_andrade
  - Lésbicas
  - Licença
  - metax
  - muy
  - não
  - Nós
  - opinião
  - opiniões
  - organização
  - orientação
  - participação
  - perseguição
  - polícia
  - política
  - prédio
  - preocupação
  - prepush
  - públicos
  - quero
  - questões
  - raça
  - react-test-renderer
  - relação
  - renderer
  - são
  - segurança
  - será
  - serão
  - shellcheck
  - técnica
  - testc
  - testu
  - testw
  - tradução
  - typoci
  - Versão
  - Vinícius
  - visão
  - vítima
  - Você
  - voluntárias
  - wbr
  - xit
