version: '3.7'

services:
  website:
    image: website
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
    volumes:
    - ./:/usr/src/app