[build]
  command = "npm run build"
  functions = "functions"
  publish = "/public"

[dev]
  command = "npm start"
  port = 8000
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = "base-uri 'self'; default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; object-src 'none'; form-action 'self'; font-src 'self' data:; connect-src 'self'; img-src 'self' data:;"
  Referrer-Policy = "no-referrer"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"