[build]
  command = "npm run build"
  functions = "functions"
  publish = "/public"

[dev]
  command = "npm start"
  port = 8000
  publish = "public"
  
[[redirects]]
  from = "/código-de-conduta"
  to = "/codigo-de-conduta"
  status = 301
