[build]
  command = "npm run build"
  functions = "functions"
  publish = "/public"

[dev]
  command = "npm start"
  port = 8000
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
  Referrer-Policy = "no-referrer"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"