backend:
  name: git-gateway
  branch: master
collections:
  - name: "team_members"
    create: true
    delete: false
    extension: yml
    format: yaml
    folder: "content/team-members"
    identifier_field: name
    label: "Time"
    slug: "{{slug}}"
    fields:
      - {label: "Nome da pessoa", name: "name", required: true, widget: "string"}
      - {label: "Papel da pessoa", name: "position", required: false, widget: "string"}
      - {label: "Cidade atual", name: "address-level2", required: true, widget: "string"}
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow
